### ISSUE TITLE
Dynamic output name

### ISSUE THREAD

**Issue by equinusocio** [amzn/style-dictionary#667] opened 2021-07-12 08:06 UTC
Hello, is there a way to configure style-dictionary in order to get the same filaname as source for the generate files?

I need to take a `light.json` source template and generate `light.json` and `light.css`, same for `dark.json` source file. So would like:

- A way to specify output settings and name for single sources
- Or a way to declare multiple source and relative platforms

```sh
src/
  light.json
  dark.json
  
# ⬇⬇⬇⬇  
  
dist
  light
     light.css
     light.json
  dark
    dark.css
    dark.json   
```

**Comment by chazzmoney** [comment] 2021-11-02 22:40
Also in #619

**Comment by chazzmoney** [comment] 2021-11-02 22:51
An example for how to do this in the current system is here:

https://github.com/amzn/style-dictionary/blob/main/examples/advanced/matching-build-files/config.js

**Comment by dbanksdesign** [comment] 2021-11-02 22:53
Yea this is a duplicate of #619. I did a very quick and dirty sample of how to do this by using the file names: https://stackblitz.com/edit/style-dictionary-example-ykhwa2?file=config.js

**Comment by dbanksdesign** [comment] 2021-12-23 00:05
Closing in favor of #619

**Closed by dbanksdesign** 2021-12-23 00:05 UTC
