### ISSUE TITLE
Transitive transforms do not work well with references that don't have `.value` at the end

### ISSUE THREAD

**Issue by six7** [amzn/style-dictionary#794] opened 2022-03-13 12:41 UTC
When you use references that do not contain .value at the end transitive transforms do not work as expected.

In the [transitive transforms example](https://github.com/amzn/style-dictionary/blob/main/examples/advanced/transitive-transforms/tokens/color/font.json5), when you swap out token references from `{color.font.primary.value}` to `{color.font.primary}` output changes so that it does not include the resolved previous reference.

**Expected output:**
```
  --color-font-primary: #000000;
  --color-font-secondary: #2c2c2c;
  --color-font-tertiary: #555555;
```

**Actual output:**
```
  --color-font-primary: #000000;
  --color-font-secondary: #2c2c2c;
  --color-font-tertiary: #2c2c2c;
```

**Comment by Sebazzz** [comment] 2022-03-14 12:15
Another example:

```json
    "fontFamilies": {
      "open-sans": {
        "value": "Open Sans",
        "type": "fontFamilies"
      }
    },
...
  "H1": {
      "fontFamily": {
        "value": "$fontFamilies.open-sans",
        "type": "fontFamily"
      },
...
```

Output:

```scss
$font-families-open-sans: Open Sans;
$h1-font-family: $fontFamilies.open-sans;
$h1-font-weight: $fontWeights.open-sans-0;
$h1-line-height: $lineHeights.0;
...

**Comment by dbanksdesign** [comment] 2022-09-25 21:05
Looks like this issue has been fixed for a bit. Closing for now, please re-open if the issue is still occurring.

**Closed by dbanksdesign** 2022-09-25 21:05 UTC
