### ISSUE TITLE
Breaking Change in 3.9.1: token.filepath now uses system path delemiter

### ISSUE THREAD

**Issue by Vampire2008** [amzn/style-dictionary#1066] opened 2023-12-08 08:28 UTC
In 3.9.1 `token.filepath` now uses system path delemiter (for Windows it '\'). It breaks some filter checks in our project. We have maked changes. But please do not release some breaking changes in patch versions.

**Comment by pinguet62** [comment] 2023-12-08 12:02
Hello 🖖
I have also a regression with `3.9.1` in Windows.
I don't known if it's linked to "`token.filepath`".

ℹ️ The version `3.9.0` with `glob@^10.3.10` fails -> probably the root cause?

**Comment by jorenbroekema** [comment] 2023-12-14 13:45
https://github.com/amzn/style-dictionary/commit/4b0b2714f72ee33bfc992cbc460be871407de4e3 seems related to this commit.

https://github.com/isaacs/node-glob/blob/main/changelog.md#1010 there seems to be a `posix` option added to make paths "/"-delimited even on windows, we might need to apply that. @Vampire2008 could you confirm perhaps by adding `posix: true` to the options at https://github.com/amzn/style-dictionary/blob/main/lib/utils/combineJSON.js#L48 (e.g. monkeypatch this in your node_modules)?

Maybe contribute a PR with this fix :) if it's indeed the fix for this regression?

**Comment by Vampire2008** [comment] 2023-12-15 05:42
I tested adding `posix: true`. It returned previous behavior.
I already adapted my code to new behavior.

**Comment by jorenbroekema** [comment] 2023-12-22 08:01
Working on this now.

https://github.com/amzn/style-dictionary/actions/runs/7288756295/job/19861941453?pr=1070 here I upgraded to latest glob and verified with windows github actions workflow that we have some failing tests related to this bug report. So currently busy making sure everything works on Windows, as well as our tests

**Comment by seanogdev** [comment] 2024-01-16 14:38
Could we get a release with this fix out?

**Comment by jorenbroekema** [comment] 2024-01-17 14:39
Created a PR, just gotta wait a bit for someone in the Amazon team to merge & release it

**Comment by jorenbroekema** [comment] 2024-01-17 17:18
Done, 3.9.2 released with fix

**Closed by jorenbroekema** 2024-01-17 17:18 UTC
Labels: bug, 3.0
